#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "========================================"
echo " apuri DevContainer セットアップ"
echo "========================================"
echo ""

# インスタンス番号の入力
while true; do
  read -p "インスタンス番号を入力してください (1-8): " INSTANCE
  if [[ "$INSTANCE" =~ ^[1-8]$ ]]; then
    break
  fi
  echo "エラー: 1〜8 の数値を入力してください"
done

# ポートオフセット計算（40000 台 / +10 刻み）
OFFSET=$(( (INSTANCE - 1) * 10 ))
AL_PORT=$(( 40001 + OFFSET ))

echo ""
echo "インスタンス番号: $INSTANCE (offset: +$OFFSET)"
echo "ポート割り当て:"
echo "  al (アプリ): $AL_PORT"
echo ""

# .devcontainer/.env の生成
cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by make setup (instance: $INSTANCE)
AL_PORT=$AL_PORT
EOF

# ルート .env の生成（アプリ側でも参照できるように）
cat > "$PROJECT_DIR/.env" <<EOF
# Auto-generated by make setup (instance: $INSTANCE)
AL_PORT=$AL_PORT
EOF

echo "生成しました:"
echo "  - $SCRIPT_DIR/.env"
echo "  - $PROJECT_DIR/.env"
echo ""
echo "次のステップ:"
echo "  1. VS Code でコマンドパレットから 'Dev Containers: Reopen in Container' を実行"
echo "  2. ホストからのログインは ./devlogin"
echo ""
